<?php
/**
 * Created by PhpStorm.
 * User: avallete
 * Date: 28/08/17
 * Time: 22:06
 */
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
}